services:
  - type: web
    name: url-shortener
    env: python
    plan: free
    buildCommand: "python3.11 -m pip install -r requirements.txt"
    startCommand: "python3.11 -m gunicorn app:app"
    runtime: python3.11
